"use client";

import { useState, useCallback, useEffect } from "react";
import {
    Conversation,
    ConversationContent,
} from "@/components/ai-elements/conversation";
import {
    PromptInput,
    PromptInputTextarea,
    PromptInputSubmit,
    PromptInputBody,
    PromptInputFooter,
} from "@/components/ai-elements/prompt-input";
import { TypingIndicator } from "@/components/chat/typing-indicator";
import { ToolCallDisplay } from "@/components/chat/tool-call-display";
import { ArtifactPreview } from "@/components/artifacts/artifact-preview";

interface MessageType {
    id: string;
    role: "user" | "assistant";
    content: string;
    toolCalls?: ToolCall[];
    artifacts?: Artifact[];
}

interface ToolCall {
    id: string;
    name: string;
    status: "pending" | "running" | "completed" | "failed";
    duration?: number;
}

interface Artifact {
    id: string;
    name: string;
    url: string;
    type: string;
    content?: string;
}

interface ChatInterfaceProps {
    chatId: string | null;
    onSelectArtifact?: (artifact: Artifact) => void;
}

// Mock messages for demonstration
const mockMessages: MessageType[] = [
    {
        id: "1",
        role: "user",
        content: "Generate a social media hygiene report for the Instagram profile @techcompany",
    },
    {
        id: "2",
        role: "assistant",
        content: "I'll analyze the Instagram profile and generate a comprehensive social media hygiene report for you.",
        toolCalls: [
            {
                id: "tc1",
                name: "analyze_instagram_profile",
                status: "completed",
                duration: 3.2,
            },
            {
                id: "tc2",
                name: "generate_hygiene_report",
                status: "completed",
                duration: 5.8,
            },
        ],
        artifacts: [
            {
                id: "a1",
                name: "Social_Media_Hygiene_Report.md",
                url: "",
                type: "text/markdown",
                content: `# Social Media Hygiene Report

## Profile: @techcompany

### Overview
- **Followers**: 12,450
- **Following**: 234
- **Posts**: 187
- **Engagement Rate**: 4.2%

### Key Findings

1. **Content Quality**: High quality visuals with consistent branding
2. **Posting Frequency**: Average 3-4 posts per week
3. **Hashtag Usage**: Effective use of industry-relevant hashtags

### Recommendations

- Increase engagement with followers through Stories
- Consider adding more behind-the-scenes content
- Optimize posting times based on audience activity

---

*Report generated by IKF AI Skills*`,
            },
        ],
    },
];

export function ChatInterface({ chatId, onSelectArtifact }: ChatInterfaceProps) {
    const [messages, setMessages] = useState<MessageType[]>(chatId ? mockMessages : []);
    const [input, setInput] = useState("");
    const [isLoading, setIsLoading] = useState(false);

    // Reset messages when chatId changes
    useEffect(() => {
        if (chatId === null) {
            setMessages([]);
        } else {
            setMessages(mockMessages);
        }
    }, [chatId]);

    const handleSubmit = useCallback(async () => {
        if (!input.trim() || isLoading) return;

        const userMessage: MessageType = {
            id: Date.now().toString(),
            role: "user",
            content: input,
        };

        setMessages((prev) => [...prev, userMessage]);
        setInput("");
        setIsLoading(true);

        // Simulate AI response
        setTimeout(() => {
            const assistantMessage: MessageType = {
                id: (Date.now() + 1).toString(),
                role: "assistant",
                content: "I'm processing your request. This is a demo response showing how the interface will work with real agent integration.",
                toolCalls: [
                    {
                        id: "demo-tc",
                        name: "process_request",
                        status: "completed",
                        duration: 2.1,
                    },
                ],
            };
            setMessages((prev) => [...prev, assistantMessage]);
            setIsLoading(false);
        }, 2000);
    }, [input, isLoading]);

    return (
        <div className="flex flex-col h-full">
            {/* Header */}
            <header className="h-14 border-b border-border flex items-center px-6 shrink-0">
                <h2 className="font-display font-semibold text-sm">IKF AI Agent</h2>
            </header>

            {/* Chat Content */}
            <Conversation className="flex-1 min-h-0">
                <ConversationContent className="p-6">
                    {messages.length === 0 ? (
                        <div className="flex flex-col items-center justify-center h-full max-w-2xl mx-auto">
                            <div className="w-12 h-12 rounded-full bg-foreground flex items-center justify-center mb-6">
                                <span className="text-background font-serif text-2xl">𝐢</span>
                            </div>
                            <h2 className="text-xl font-semibold mb-2">How can I help you today?</h2>
                            <p className="text-muted-foreground text-sm mb-8">Choose a suggestion or type your own request</p>
                            <div className="grid grid-cols-2 gap-3 w-full">
                                <button
                                    onClick={() => setInput("Generate a social media hygiene report for @techcompany")}
                                    className="text-left p-4 rounded-xl border border-border bg-card hover:bg-muted transition-colors"
                                >
                                    <p className="font-medium text-sm">Social Media Analysis</p>
                                    <p className="text-xs text-muted-foreground mt-1">Generate hygiene report for a profile</p>
                                </button>
                                <button
                                    onClick={() => setInput("Analyze candidate resumes and rank them")}
                                    className="text-left p-4 rounded-xl border border-border bg-card hover:bg-muted transition-colors"
                                >
                                    <p className="font-medium text-sm">Resume Screening</p>
                                    <p className="text-xs text-muted-foreground mt-1">Analyze and rank candidate resumes</p>
                                </button>
                                <button
                                    onClick={() => setInput("Research competitor landscape for my industry")}
                                    className="text-left p-4 rounded-xl border border-border bg-card hover:bg-muted transition-colors"
                                >
                                    <p className="font-medium text-sm">Market Research</p>
                                    <p className="text-xs text-muted-foreground mt-1">Research competitor landscape</p>
                                </button>
                                <button
                                    onClick={() => setInput("Create a project proposal document")}
                                    className="text-left p-4 rounded-xl border border-border bg-card hover:bg-muted transition-colors"
                                >
                                    <p className="font-medium text-sm">Document Generation</p>
                                    <p className="text-xs text-muted-foreground mt-1">Create proposals and reports</p>
                                </button>
                            </div>
                        </div>
                    ) : (
                        <div className="space-y-6 max-w-4xl mx-auto">
                            {messages.map((message) => (
                                <div
                                    key={message.id}
                                    className={`flex ${message.role === "user" ? "justify-end" : "justify-start"}`}
                                >
                                    <div className={`max-w-[80%] ${message.role === "user" ? "text-right" : "text-left"}`}>
                                        {message.role === "assistant" ? (
                                            <div className="prose prose-invert prose-sm">
                                                {message.content}
                                            </div>
                                        ) : (
                                            <p className="text-foreground bg-muted px-4 py-3 rounded-xl">{message.content}</p>
                                        )}

                                        {/* Tool Calls */}
                                        {message.toolCalls && message.toolCalls.length > 0 && (
                                            <div className="mt-3 space-y-2">
                                                {message.toolCalls.map((toolCall) => (
                                                    <ToolCallDisplay key={toolCall.id} toolCall={toolCall} />
                                                ))}
                                            </div>
                                        )}

                                        {/* Artifacts */}
                                        {message.artifacts && message.artifacts.length > 0 && (
                                            <div className="mt-4 space-y-3">
                                                {message.artifacts.map((artifact) => (
                                                    <div
                                                        key={artifact.id}
                                                        onClick={() => onSelectArtifact?.(artifact)}
                                                        className="w-full cursor-pointer"
                                                    >
                                                        <ArtifactPreview artifact={artifact} />
                                                    </div>
                                                ))}
                                            </div>
                                        )}
                                    </div>
                                </div>
                            ))}
                            {isLoading && (
                                <div className="flex justify-start">
                                    <TypingIndicator />
                                </div>
                            )}
                        </div>
                    )}
                </ConversationContent>
            </Conversation>

            {/* Input Area */}
            <div className="border-t border-border p-4 shrink-0">
                <div className="max-w-4xl mx-auto">
                    <PromptInput
                        onSubmit={() => handleSubmit()}
                        className="bg-input rounded-xl border border-border"
                    >
                        <PromptInputBody>
                            <PromptInputTextarea
                                value={input}
                                onChange={(e) => setInput(e.target.value)}
                                placeholder="Ask the Meta Agent to perform a task…"
                                disabled={isLoading}
                                onKeyDown={(e) => {
                                    if (e.key === "Enter" && !e.shiftKey) {
                                        e.preventDefault();
                                        handleSubmit();
                                    }
                                }}
                                className="min-h-[52px] resize-none"
                            />
                        </PromptInputBody>
                        <PromptInputFooter className="justify-end p-2">
                            <PromptInputSubmit disabled={isLoading || !input.trim()} />
                        </PromptInputFooter>
                    </PromptInput>
                </div>
            </div>
        </div>
    );
}
